server:
  port: 8090
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: brad0135@gmail.com
    password: mqscqrlrqxchxhih
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/ntlsoft?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
#    username: root
#    password: 
    username: sbsst
    password: sbs123414 
    
mybatis:
  type-aliases-package: com.ntlsoft.dto
custom:
  siteMainUri: http://localhost:8024/
  siteName: NTLsoft
  emailFrom: no-reply@localhost
  emailFromName: NTL-soft manager
  genFileDirPath: C:/work/com.ntlsoft-file
  logging:
    dir: log
    level: debug